import Link from 'next/link';
import ResearchPage from '@/components/ResearchPage';
import MemberOutcomes from '@/components/MemberOutcomes';
import { pageMetadata } from '@/lib/metadata';
import { ArrowUpRight } from 'lucide-react';

const intro = 'Learn to ask better questions, work with imperfect data, and explain what the evidence can—and cannot—tell us.';
export const metadata = pageMetadata('The student research experience', 'Explore student economic research at Rutgers Economics Labs: public data, Python and R, econometrics, reproducible analysis, and communicating findings.', '/student-experience');
const examples = [
  { name: 'Start with a real data source', label: 'Python & Census API workshop', text: 'The workshop fetches state population estimates from the American Community Survey, handles request errors, and parses the response. It is a concrete starting point for learning how a public dataset becomes something you can analyze.', skill: 'Practice: API requests, data definitions, JSON, and checking your inputs.', url: 'https://github.com/Rutgers-Economics-Labs/python_api_workshop' },
  { name: 'Test the argument—not just the code', label: 'NJ climate risk & municipal bonds', text: 'The NJDEP project joins municipal climate exposure, financial data, and bond-market information into a panel. Its documented workflow includes difference-in-differences models, pre-trend checks, and a dashboard. The README calls the evidence exploratory and explains why it is not a final causal estimate.', skill: 'Practice: data matching, econometrics, diagnostics, and honest interpretation.', url: 'https://github.com/Rutgers-Economics-Labs/NJDEPClimateRiskSp2026' },
  { name: 'Build an analysis in pieces', label: 'Clean energy funding', text: 'The clean-energy repository contains separate notebooks for registrations, battery-cost modeling, and analysis, alongside data and graphs. It shows how a research question can be broken into smaller, inspectable pieces of work.', skill: 'Practice: notebooks, modeling, visualization, and organizing research artifacts.', url: 'https://github.com/Rutgers-Economics-Labs/CleanEnergyFundingF24' },
  { name: 'Make research easier to reproduce', label: 'RAIL · internal research tooling', text: 'RAIL is an open-source, agent-assisted research platform developed from REL. It keeps plans, data sources, assumptions, analysis artifacts, and integrity checks alongside code. It is an example of the group’s technical tooling work—not a required tool for every team.', skill: 'Practice: research software, source provenance, testing, and human review of AI-assisted work.', url: 'https://github.com/Rutgers-Economics-Labs/RutgersAgenticIntelligenceLabs' },
];

export default function StudentExperiencePage() {
  return <ResearchPage title="The student research experience" eyebrow="Curiosity → evidence → explanation" intro={intro} path="/student-experience">
    <section className="research-split"><div><h2>More than a finished notebook.</h2><p>At Rutgers Economics Labs, students contribute to economic and policy research in teams. The work can involve reading prior research, finding usable data, writing analysis code, testing assumptions, and communicating results to people outside the team.</p><p>You do not need to do every part on day one. The goal is to take responsibility for a meaningful part of a question and understand how it connects to the rest of the research.</p><Link className="research-button" href="/apply">Check application availability <ArrowUpRight aria-hidden="true" className="w-4 h-4" /></Link></div><aside className="research-note"><p className="research-eyebrow">What you bring</p><h3>Interest in the question. Care with the evidence.</h3><p>Students from different majors are welcome. Quantitative reasoning, willingness to learn, clear communication, and following through on team commitments matter alongside technical skills.</p><p>Project assignments, tools, and expectations vary by team. Confirm the current scope and commitment during recruiting.</p></aside></section>
    <section><p className="research-eyebrow">A research workflow</p><h2>What the work can look like.</h2><ol className="research-steps research-workflow">
      <li><h3>Understand the question</h3><p>Read the literature, clarify the policy context, and define an answerable question with your team.</p></li>
      <li><h3>Make the data usable</h3><p>Inspect sources, reconcile geography and time periods, document missing values, and build a dataset you can explain.</p></li>
      <li><h3>Analyze and challenge</h3><p>Write Python or R code, visualize patterns, check assumptions, and distinguish an association from a causal claim.</p></li>
      <li><h3>Communicate and hand off</h3><p>Explain methods and limitations, respond to feedback, and leave organized code and documentation that someone else can follow.</p></li>
    </ol></section>
    <section><p className="research-eyebrow">Explore the work</p><h2>Examples from our public repositories.</h2><p>These examples show the kinds of skills represented in REL’s work. They are not a fixed curriculum or a promise of assignment to a specific project.</p><div className="research-grid research-examples">{examples.map(example => <article className="research-card" key={example.url}><p className="research-eyebrow">{example.label}</p><h3>{example.name}</h3><p>{example.text}</p><p className="research-practice">{example.skill}</p><a className="research-text-link" href={example.url} target="_blank" rel="noopener noreferrer">Explore the repository <ArrowUpRight aria-hidden="true" className="w-4 h-4" /></a></article>)}</div><p className="research-caption">Public repository documentation reviewed September 5, 2026. Repositories evolve; private partner materials and personal contact records are not reproduced here.</p></section>
    <MemberOutcomes />
    <section className="research-closing"><h2>Find the question you want to work on.</h2><p>Explore past projects, meet the team, and check current recruiting information.</p><Link className="research-button" href="/projects">Explore REL projects <ArrowUpRight aria-hidden="true" className="w-4 h-4" /></Link><Link className="research-text-link" href="/people">Meet the team <ArrowUpRight aria-hidden="true" className="w-4 h-4" /></Link><Link className="research-text-link" href="/resources">Learning resources <ArrowUpRight aria-hidden="true" className="w-4 h-4" /></Link></section>
  </ResearchPage>;
}
